<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Genre as Genre;
use Doctrine\ORM\EntityRepository;
/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends EntityRepository
{
}
