<?php

namespace AppBundle\Repository;

/**
 * VolumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolumeRepository extends \Doctrine\ORM\EntityRepository
{
}
